### PR TITLE
Create the NeedIt Application Module Completed

### PR DESCRIPTION
**Pull request by Iconoclast-70**

### CODE REVIEW

**Comment by Iconoclast-70** [comment]
Create the NeedIt Application Module Completed

**Comment by Iconoclast-70** [comment]
Create the NeedIt Application Module Completed

**Comment by bsweets** [comment]
Thanks for submitting this, but we do not accept pull requests against the ServiceNow training primary repository. If you want to access your specific work from a learning module, we recommend that you do not merge the changes into the primary repository. If you still want to merge, please select **your fork** as the *base repository* in GitHub before making the pull request.

**Comment by Iconoclast-70** [comment]
Sorry about that, I'm not sure how that happened lol.  I did fork the
repository here  https://github.com/Iconoclast-70/devtraining-needit-rome
I'm used to updating my repositories from my virtual machine on the command
line, I'm new to ServiceNow development.

Best regards,

Phil

**Pull request closed without merging**
